name: Monthly Energy Data Scraper

on:
  schedule:
    - cron: "0 3 1 * *"  # Runs at 03:00 UTC on the 1st of each month
  workflow_dispatch:     # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas

      - name: Run scraper
        run: python scrape_energy_consumption.py

      - name: Commit and push data update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/empire_energy_consumption_*.csv
          git commit -m "Update empire energy data ($(date -u '+%Y-%m-%d'))" || echo "No changes to commit"
          git push
