name: Scrape Market Cap Data

on:
  schedule:
    # Run every day at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allows manual trigger from Actions tab
  push:
    branches: [ main ]  # Run on push to test

# CRITICAL: Grant write permissions to GITHUB_TOKEN
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install selenium pandas PyGithub webdriver-manager
        
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Run scraper
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use Personal Access Token instead
      run: |
        python main.py
        
    - name: Commit and push if changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add data/countries_marketcap.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update market cap data [skip ci]" && git push)
        
    - name: Upload debug files
      if: always()  # Run even if scraper fails
      uses: actions/upload-artifact@v4
      with:
        name: debug-output
        path: |
          *.html
          *.png
          *.csv
